[package]
name = "blog_website"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
serde = "1.0.218"
tokio = {version = "1.43.0", features = ["full"]}
sqlx = "0.8.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
